dataset:
  name: "hospital"
  prediction_length: -1
  windows: 1
finetuning:
  time_limit: 100
  batch_size: 2
  learning_rate: 0.000005
  l2_sp_lambda: 0.0001
  weight_decay: 0.0
  update_every_n_steps: 1
  validation:
    validate_every_n_steps: 1
    ts_val_amount: 1
    early_stopping:
      min_patience: 100
      max_patience: 200
  checkpoint_to_save: test_ckpt